[package]
name = "bufr-read"
version = "0.1.0"
authors = ["Ryan <rnleach@users.noreply.github.com>"]
edition = "2018"
publish = false

[dependencies]
eccodes-sys = {version = "2.10.0", git = "https://github.com/rnleach/eccodes-sys.git", branch="dev"}
libc = "0.2"
optional = "0.5"
