[package]
name = "bufr-read"
<<<<<<< HEAD
version = "0.2.0"
=======
version = "0.2.1"
>>>>>>> dev
authors = ["Ryan <rnleach@users.noreply.github.com>"]
edition = "2018"
publish = false

[dependencies]
<<<<<<< HEAD
eccodes-sys = {version = "2.12.0", git = "https://github.com/rnleach/eccodes-sys.git", tag="v2.12.0"}
=======
eccodes-sys = {version = "2.12.1", git = "https://github.com/rnleach/eccodes-sys.git", tag="v2.12.1"}
>>>>>>> dev
libc = "0.2"
optional = "0.5"
