[package]
name = "bufr"
version = "0.0.1"
authors = ["Ryan <rnleach@users.noreply.github.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2"
libc = "0.2"
eccodes-sys = {version = "^0.1", git = "https://github.com/rnleach/eccodes-sys.git", branch ="master" }

